//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bundle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bundle()
        {
            this.ProductToBundle = new HashSet<ProductToBundle>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ClasificationId { get; set; }
        public System.Guid ImageId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual Clasification Clasification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductToBundle> ProductToBundle { get; set; }
        public virtual Image Image { get; set; }
    }
}
