//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public System.Guid Id { get; set; }
        public System.Guid LocationId { get; set; }
        public System.Guid ProductStatusId { get; set; }
        public Nullable<int> MinimumInventoryLevel { get; set; }
        public Nullable<int> OnHandInventoryLevel { get; set; }
        public Nullable<int> AvailableInventoryLevel { get; set; }
        public Nullable<int> OnReserveInventoryLevel { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual ProductStatus ProductStatus { get; set; }
    }
}
