//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid OrderId { get; set; }
        public System.Guid ProductId { get; set; }
        public System.Guid BrandId { get; set; }
        public System.Guid PriceListId { get; set; }
        public string Quantity { get; set; }
        public string Name { get; set; }
        public string UnitCost { get; set; }
        public string Freight { get; set; }
        public string Subtotal { get; set; }
        public string EstimatedDeliveryDate { get; set; }
        public string Warehouse { get; set; }
        public string StorageLocation { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Order Order { get; set; }
        public virtual PriceList PriceList { get; set; }
        public virtual Product Product { get; set; }
    }
}
