//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point
    {
        public System.Guid Id { get; set; }
        public System.Guid ClientId { get; set; }
        public System.Guid PointTypeId { get; set; }
        public System.Guid OrderId { get; set; }
        public long Amount { get; set; }
        public int Active { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Order Order { get; set; }
        public virtual PointType PointType { get; set; }
    }
}
