//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceListToCluster
    {
        public System.Guid Id { get; set; }
        public System.Guid ClusterId { get; set; }
        public System.Guid PriceListId { get; set; }
    
        public virtual Cluster Cluster { get; set; }
        public virtual PriceList PriceList { get; set; }
    }
}
